module.exports = {
  // Usuario
  USD01: "Crear perfil cliente",
  USD02: "Agregar producto al carrito",
  USD03: "Eliminar producto al carrito",
  USD04: "Visualizar producto del carrito",
  USD05: "Calculo total de compras",
  USD06: "Listar productos",
  USD07: "Mostrar precio e imagen",
  USD08: "Galeria de imagenes",
  USD09: "Mostrar descripción y técnica",
  USD10: "Diseño acceso a catalogo",
  USD11: "Mostrar mision y valores",
  USD12: "Selección método de pago",
  USD13: "Mensaje confirmación pedido",
  USD14: "Formulario de datos de envio",
  UCD15: "Resumen de compra",
  USD16: "Visualizar perfil del artesano",
  USD17: "Mensaje de confirmacion de envio",
  USD18: "Formulario de contacto",
  USD19: "Mostrar redes y contacto",
  USD20: "Filtro por tipo de artesano",
  USD21: "Informacion del artesano",
  USD22: "Indicador de fragilidad",
  USD23: "Seleccion historia y comunidad",
  USD24: "Listar productos del artesano",
  USD25: "Etiqueta producto único",
  USD26: "Implementar productos destacados",
  USD27: "Galeria imagenes del artesano",
  USD28: "Mostrar ubicación",

  // Administrador
  ADM01: "Inicio de sesión administrador",
  ADM02: "Dar de alta producto",
  ADM03: "Consultar productos",
  ADM04: "Actualizar producto",
  ADM05: "Eliminar producto",
  ADM06: "Imprimir listado productos",
  ADM07: "Control de stock",
  ADM08: "Registrar proveedor",
  ADM09: "Consultar proveedor",
  ADM10: "Actualizar proveedor",
  ADM11: "Eliminar proveedor",
  ADM12: "Registrar compra",
  ADM13: "Registrar método de pago",
  ADM14: "Registrar venta",
  ADM15: "Consultar ventas (Dashboard)",
  ADM16: "Agregar perfil empresa",
  ADM17: "Editar perfil empresa",
  ADM18: "Visualizar perfil empresa",
  ADM19: "Clasificar productos",
  ADM20: "Crear usuario",
  ADM21: "Consultar usuario",
  ADM22: "Eliminar usuario",
  ADM23: "Asignar roles",
  ADM24: "Directorio de artesanos/proveedores",
  ADM25: "Filtrar ventas",
  ADM26: "Adjuntar comprobante de pago",
  ADM27: "Categorización de proveedores",
  ADM28: "Interfaz limitada para Vendedor",
  ADM29: "Generar reporte de ventas",
  ADM30: "Reporte de productos \"Top Sellers\"",
  ADM31: "Aplicar descuentos",
  ADM32: "Generar ticket de venta en PDF",
  ADM33: "Asignar estatus proveedor",
};
