-- Ejecuta este script en Supabase SQL Editor para habilitar el formulario de contacto.
-- El error actual ocurre porque la tabla public.mensajes_contacto no existe.

create table if not exists public.mensajes_contacto (
  id_mensaje bigint generated by default as identity primary key,
  nombre text not null,
  email text not null,
  mensaje text not null,
  estado text not null default 'pendiente',
  creado_en timestamptz not null default now()
);

alter table public.mensajes_contacto enable row level security;

drop policy if exists "Permitir crear mensajes de contacto anonimos"
  on public.mensajes_contacto;

create policy "Permitir crear mensajes de contacto anonimos"
  on public.mensajes_contacto
  for insert
  to anon
  with check (
    length(trim(nombre)) > 0
    and position('@' in email) > 1
    and length(trim(mensaje)) >= 10
  );

